name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Jalankan setiap kali push ke main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Configure Git
        run: |
          git config --global user.email "runtufandi@gmail.com"
          git config --global user.name "anru"

      - name: Deploy to GitHub Pages
        run: npm run deploy